version: '2.2'
services:
  node:
    image: "datastax/dse-server:6.8.5"
    environment:
      - DS_LICENSE=accept
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock: -1
    ports:
      - "7199:7199"
      - "9042:9042"
    container_name: "dse"
    healthcheck:
      test: [ "CMD", "cqlsh", "-e describe keyspaces" ]
      interval: 15s
      timeout: 10s
      retries: 10
  app:
    image: "bank-of-paris/banky:latest"
    container_name: "banky"
    ports:
      - "8081:8081"
    depends_on:
      node:
        condition: service_healthy